# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.9"

services:

  mysql:
    image: mysql:8

    container_name: mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb

    ports:
      - "3306:3306"

    volumes:
      # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
       - mysql-data 

    networks:
        - student-management-system-network   

  backend:

    build: ./backend

    container_name: backend

    ports:
      - "5000:5000"

    depends_on:
      - mysql

    networks:
        - student-management-system-network   

  frontend:

    build: ./frontend

    container_name: frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
        - student-management-system-network   

networks:
  default:
    name: student-management-system-network